language: node_js
node_js
-14.17.0
cache: npm

# before_install:
install:
  - npm ci
#   - npm i -g
# before_script:
script:
  - npm test
  - npm run build
# after_success:
# after_failure:
# after_script:
# before_deploy:
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: gh-pages
